### ISSUE TITLE
Bootstrap Component not Registered

### ISSUE THREAD

**Issue by michaelr1300** [marcohartono/Project-Clairity-V2#2]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html

Project ini menggunakan vite, jadi untuk register component bootstrap (e.g. b-row, b-col) perlu tambahan step seperti di dokumentasi. 

Bisa install unplugin-vue-components dulu, lalu tambahkan di config vite

![image](https://github.com/user-attachments/assets/9cc8288e-561f-450d-9ebb-aeadac7419a9)

**Comment by marcohartono** [comment]
sudah berhasil
